import { useId, useRef, useState, type PointerEvent, type ReactNode } from 'react'
import { Check, CircleCheck, Copy, Info, TriangleAlert } from 'lucide-react'

/** Same artwork as resources/icon.png (generated by scripts/gen-icons.mjs). */
export function Logo({ size = 32 }: { size?: number }) {
  const gradient = `logo-${useId().replace(/[^\w-]/g, '')}`
  return (
    <svg width={size} height={size} viewBox="0 0 64 64" aria-hidden="true">
      <defs>
        <linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#4d8af0" />
          <stop offset="1" stopColor="#2b5fd9" />
        </linearGradient>
      </defs>
      <rect x="2" y="2" width="60" height="60" rx="14" fill={`url(#${gradient})`} />
      <g fill="#fff">
        <path d="M15 23a6 6 0 0 1 6-6h22a6 6 0 0 1 6 6v5H15z" />
        <rect x="22" y="12" width="4" height="9" rx="2" />
        <rect x="38" y="12" width="4" height="9" rx="2" />
      </g>
      <g fill="none" stroke="#fff" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round">
        <rect x="15" y="17" width="34" height="32" rx="6" />
        <path d="M24 37l5 5 11-11" />
      </g>
    </svg>
  )
}

export function Toggle(props: { checked: boolean; label: string; disabled?: boolean; onChange: (checked: boolean) => void }) {
  return (
    <button
      type="button"
      role="switch"
      className="switch"
      aria-checked={props.checked}
      aria-label={props.label}
      disabled={props.disabled}
      onClick={() => props.onChange(!props.checked)}
    />
  )
}

const CALLOUT_ICONS = { ok: CircleCheck, info: Info, warn: TriangleAlert, error: TriangleAlert }

export function Callout(props: { kind: keyof typeof CALLOUT_ICONS; title?: string; children?: ReactNode }) {
  const Icon = CALLOUT_ICONS[props.kind]
  return (
    <div className={`callout ${props.kind}`} role={props.kind === 'error' ? 'alert' : undefined}>
      <Icon size={16} />
      <div className="callout-body">
        {props.title && <div className="callout-title">{props.title}</div>}
        {props.children}
      </div>
    </div>
  )
}

/** A shell command with a copy button. */
export function Command({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const copy = (): void => {
    void navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    })
  }
  return (
    <span className="command">
      <code>{text}</code>
      <button type="button" className="icon-button" title="Kopieren" aria-label="Befehl kopieren" onClick={copy}>
        {copied ? <Check size={14} /> : <Copy size={14} />}
      </button>
    </span>
  )
}

/**
 * The grip between two areas: dragging it makes one of them wider or narrower. Also works with
 * the arrow keys; a double click goes back to the default width.
 */
export function ResizeHandle(props: { label: string; onDrag: (clientX: number) => void; onStep: (delta: number) => void; onReset?: () => void }) {
  const dragging = useRef(false)
  const stop = (event: PointerEvent<HTMLDivElement>): void => {
    if (!dragging.current) return
    dragging.current = false
    if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId)
    document.body.classList.remove('resizing')
  }
  return (
    <div
      role="separator"
      aria-orientation="vertical"
      aria-label={props.label}
      title={`${props.label}: ziehen zum Verstellen, Doppelklick setzt zurück`}
      tabIndex={0}
      className="resize-handle"
      onPointerDown={(event) => {
        if (event.button !== 0) return
        event.preventDefault()
        dragging.current = true
        event.currentTarget.setPointerCapture(event.pointerId)
        // Over a PDF the iframe would swallow the mouse; body.resizing switches that off.
        document.body.classList.add('resizing')
      }}
      onPointerMove={(event) => {
        if (dragging.current) props.onDrag(event.clientX)
      }}
      onPointerUp={stop}
      onPointerCancel={stop}
      onLostPointerCapture={stop}
      onDoubleClick={props.onReset}
      onKeyDown={(event) => {
        if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') return
        event.preventDefault()
        props.onStep(event.key === 'ArrowLeft' ? -16 : 16)
      }}
    />
  )
}
